services:
  # Optional Postgres container (runs only if --profile internaldb is used)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["internaldb"]   # 👈 Only runs if you specify --profile internaldb

  web:
    image: ${IMAGE_NAME}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:${APP_INTERNAL_PORT}"
      ASPNETCORE_PATHBASE: ${ASPNETCORE_PATHBASE}
      ConnectionStrings__Postgres: ${CONNECTION_STRING_POSTGRES}
    ports:
      - "${APP_HOST_BIND}:${APP_HOST_PORT}:${APP_INTERNAL_PORT}"
    restart: unless-stopped

volumes:
  pgdata:
